export const allTeturesKeys = {
  shipBlue: "shipBlue",
  shipBlue2: "shipBlue2",
  bomb: "bomb",
  musicOn: "musicOn",
  musicOff: "musicOff",
  effectsOn: "effectsOn",
  effectsOff: "effectsOff",
  enemyShip: "enemyShip",
  man: "man",
  man2: "man2",
  woman: "woman",
  tombStone1: "tombStone1",
  tombStone2: "tombStone2",
  spaceShip: "spaceShip",
  bullet1: "bullet1",
  bullet2: "bullet2",
  explosion: "explosion",
  explosion1: "explosion1",
  explosion2: "explosion2",
  explosion3: "explosion3",
};

const appTextures = {
  [allTeturesKeys.shipBlue]: "assets/sprites/enemy/shipBlue.png",
  [allTeturesKeys.shipBlue2]: "assets/sprites/enemy/shipBlue2.png",
  [allTeturesKeys.bomb]: "assets/sprites/bomb.png",
  [allTeturesKeys.musicOn]: "assets/sprites/ui/music_on.png",
  [allTeturesKeys.musicOff]: "assets/sprites/ui/music_off.png",
  [allTeturesKeys.effectsOn]: "assets/sprites/ui/volume_on.png",
  [allTeturesKeys.effectsOff]: "assets/sprites/ui/volume_off.png",
  [allTeturesKeys.enemyShip]: "assets/sprites/enemy/shipBlue.png",
  [allTeturesKeys.man]: "assets/sprites/people/man.png",
  [allTeturesKeys.man2]: "assets/sprites/people/man2.png",
  [allTeturesKeys.woman]: "assets/sprites/people/woman.png",
  [allTeturesKeys.tombStone1]: "assets/sprites/people/TombStone1.png",
  [allTeturesKeys.tombStone2]: "assets/sprites/people/TombStone2.png",
  [allTeturesKeys.spaceShip]: "assets/sprites/player.png",
  [allTeturesKeys.bullet1]: "assets/sprites/bullets/bullet1.json",
  [allTeturesKeys.bullet2]: "assets/sprites/bullets/bullet2.json",
  [allTeturesKeys.explosion]: "assets/sprites/explosion/explosion.json",
  [allTeturesKeys.explosion1]: "assets/sprites/explosion/explosion1.json",
  [allTeturesKeys.explosion2]: "assets/sprites/explosion/explosion2.json",
  [allTeturesKeys.explosion3]: "assets/sprites/explosion/explosion3.json",
};

export default appTextures;
